name: STRs-in-CRC
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - scipy
  - seaborn
  - biopython
  - statsmodels
  - polars
  - pyarrow
  - pandas
  - notebook
  - numpy
  - scikit-learn
